name: Deploy Yii2 App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: SSH and Run Ansible
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          # Check if ansible exists, if not install
          if ! command -v ansible &> /dev/null
          then
            echo "Ansible not found. Installing..."
            sudo apt update
            sudo apt install software-properties-common -y
            sudo add-apt-repository --yes --update ppa:ansible/ansible
            sudo apt install ansible -y
          else
            echo "Ansible is already installed."
          fi

          # Proceed with your deployment
          cd /home/ubuntu/pearlThoughts
          ansible-playbook -i inventory.ini playbook.yml
